Add support for react-native-webrtc
TeamAround/simple-peer pull request #1
Opened 2022-01-21 10:38 UTC by gerhardberger

This PR skips parts of simple-peer where methods would be called that are not supported in react-native-webrtc and falls back to older methods where those are supported by react-native-webrtc.

2022-01-21 11:03 UTC, jmillan commented on index.js
> +          if (!this.initiator && !this._isReactNativeWebrtc) this._requestMissingTransceivers()
Do we know the implications of not calling `_requestMissingTransceivers()` when in react native and not initiator?

2022-01-21 11:04 UTC, jmillan commented on package.json
> -    "wrtc": "^0.4.7",
why?

2022-01-21 11:32 UTC, gerhardberger commented on package.json
> -    "wrtc": "^0.4.7",
sadly this module is not compatible with arm mac :(

2022-01-21 11:34 UTC, gerhardberger commented on index.js
> +          if (!this.initiator && !this._isReactNativeWebrtc) this._requestMissingTransceivers()
looking at `_requestMissingTransceivers` it's iterates through the already added transceivers to the PC which in our case should be empty since we dont use transceivers here

2022-01-21 11:40 UTC, jmillan commented on package.json
> -    "wrtc": "^0.4.7",
Indeed we are not using it anyway.., but without this change we may be able to create a PR to mainstream, which is good.

2022-01-21 11:41 UTC, jmillan commented
@gerhardberger, I'm OK with this.

Once proven working I would vote for creating a PR to mainstream so we don't need the fork? WDYT?

2022-01-21 11:41 UTC, jmillan approved these changes

2022-01-21 14:45 UTC, gerhardberger commented
@jmillan definitely I will do an upstream PR. but I checked the repo and its not super active so not expecting anything fast

2022-01-21 15:53 UTC, ibc requested changes

2022-01-21 15:53 UTC, ibc commented on index.js
>    removeTrack (track, stream) {
I think we need removeTrack, otherwise it's gonna leak. Here you can remove the stream vía pc.removeStream(), then, in case there are other tracks in the given stream others than the one being removed, remove the track from the stream and call pc.addStream().

2022-01-21 15:57 UTC, gerhardberger commented on index.js
>    removeTrack (track, stream) {
I dont get it, what do i need to do?

2022-01-24 21:58 UTC, gerhardberger commented on index.js
>    removeTrack (track, stream) {
added it, please check

2022-01-25 19:39 UTC, ibc approved these changes

2022-01-26 09:37 UTC, merged